export const TEXT = 'TEXT'
export const NUMBER = 'NUMBER'
export const COMPOUND = 'COMPOUND'
export const SELECT = 'SELECT'
export const DATE = 'DATE'
export const MEASUREMENT = 'MEASUREMENT'
export const MULTILANGUAGE = 'MULTILANGUAGE'